# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <kotlyar562@gmail.com>
#
# SPDX-License-Identifier: MIT

feature:
  - head-branch: ["^(feat|feature)/"]

bug:
  - head-branch: ["^(fix|bugfix|hotfix)/"]

security:
  - head-branch: ["^security/"]

ci:
  - head-branch: ["^(ci|infra)/"]

chore:
  - head-branch: ["^(chore|refactor|docs)/"]
